[package]
name = "psi-network"
version = "0.1.0"

[lib]
name = "psi_network"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
p256 = { version = "0.13.2", features = ["ecdh"] }
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks.git", package = "lambdaworks-math" }